// <auto-generated/>
using KiotaPosts.Client.Api.Renapo.Grupo;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Renapo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\renapo
    /// </summary>
    public class RenapoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The grupo property</summary>
        public KiotaPosts.Client.Api.Renapo.Grupo.GrupoRequestBuilder Grupo
        {
            get => new KiotaPosts.Client.Api.Renapo.Grupo.GrupoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.RenapoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenapoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.RenapoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RenapoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo", rawUrl)
        {
        }
    }
}
