// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\grupo\obtener-rfc
    /// </summary>
    public class ObtenerRfcRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerRfcRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/obtener-rfc{?curp*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerRfcRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/obtener-rfc{?curp*}", rawUrl)
        {
        }
        /// <summary>
        /// Obtiene el RFC Oficial registrado en el SAT, mediante el envio de curp_Nota: no se muestran resultados de RFC sin registro_
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcPostResponse?> PostAsObtenerRfcPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcPostResponse> PostAsObtenerRfcPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcPostResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene el RFC Oficial registrado en el SAT, mediante el envio de curp_Nota: no se muestran resultados de RFC sin registro_
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsObtenerRfcPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfc5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene el RFC Oficial registrado en el SAT, mediante el envio de curp_Nota: no se muestran resultados de RFC sin registro_
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obtiene el RFC Oficial registrado en el SAT, mediante el envio de curp_Nota: no se muestran resultados de RFC sin registro_
        /// </summary>
        public class ObtenerRfcRequestBuilderPostQueryParameters 
        {
            /// <summary>Clave Unica de Registro de Poblacion</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("curp")]
            public string? Curp { get; set; }
#nullable restore
#else
            [QueryParameter("curp")]
            public string Curp { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ObtenerRfcRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder.ObtenerRfcRequestBuilderPostQueryParameters>
        {
        }
    }
}
