// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral
{
    #pragma warning disable CS1591
    public class HistorialLaboralPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>HTTP URL de la constancia</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Constancia { get; set; }
#nullable restore
#else
        public string Constancia { get; set; }
#endif
        /// <summary>The curp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Curp { get; set; }
#nullable restore
#else
        public string Curp { get; set; }
#endif
        /// <summary>The historialLaboral property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral>? HistorialLaboral { get; set; }
#nullable restore
#else
        public List<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral> HistorialLaboral { get; set; }
#endif
        /// <summary>The nombre property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nombre { get; set; }
#nullable restore
#else
        public string Nombre { get; set; }
#endif
        /// <summary>The nss property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nss { get; set; }
#nullable restore
#else
        public string Nss { get; set; }
#endif
        /// <summary>The numeroDeSerie property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumeroDeSerie { get; set; }
#nullable restore
#else
        public string NumeroDeSerie { get; set; }
#endif
        /// <summary>The secuenciaNotorial property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecuenciaNotorial { get; set; }
#nullable restore
#else
        public string SecuenciaNotorial { get; set; }
#endif
        /// <summary>The selloDigital property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelloDigital { get; set; }
#nullable restore
#else
        public string SelloDigital { get; set; }
#endif
        /// <summary>The semanasCotizadas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_semanasCotizadas? SemanasCotizadas { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_semanasCotizadas SemanasCotizadas { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data"/> and sets the default values.
        /// </summary>
        public HistorialLaboralPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "constancia", n => { Constancia = n.GetStringValue(); } },
                { "curp", n => { Curp = n.GetStringValue(); } },
                { "historialLaboral", n => { HistorialLaboral = n.GetCollectionOfObjectValues<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral>(KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral.CreateFromDiscriminatorValue)?.ToList(); } },
                { "nombre", n => { Nombre = n.GetStringValue(); } },
                { "nss", n => { Nss = n.GetStringValue(); } },
                { "numeroDeSerie", n => { NumeroDeSerie = n.GetStringValue(); } },
                { "secuenciaNotorial", n => { SecuenciaNotorial = n.GetStringValue(); } },
                { "selloDigital", n => { SelloDigital = n.GetStringValue(); } },
                { "semanasCotizadas", n => { SemanasCotizadas = n.GetObjectValue<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_semanasCotizadas>(KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_semanasCotizadas.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("constancia", Constancia);
            writer.WriteStringValue("curp", Curp);
            writer.WriteCollectionOfObjectValues<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral>("historialLaboral", HistorialLaboral);
            writer.WriteStringValue("nombre", Nombre);
            writer.WriteStringValue("nss", Nss);
            writer.WriteStringValue("numeroDeSerie", NumeroDeSerie);
            writer.WriteStringValue("secuenciaNotorial", SecuenciaNotorial);
            writer.WriteStringValue("selloDigital", SelloDigital);
            writer.WriteObjectValue<KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_semanasCotizadas>("semanasCotizadas", SemanasCotizadas);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
