// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral
{
    #pragma warning disable CS1591
    public class HistorialLaboralPostResponse_data_historialLaboral : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entidadFederativa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntidadFederativa { get; set; }
#nullable restore
#else
        public string EntidadFederativa { get; set; }
#endif
        /// <summary>The fechaAlta property</summary>
        public Date? FechaAlta { get; set; }
        /// <summary>The fechaBaja property</summary>
        public Date? FechaBaja { get; set; }
        /// <summary>The nombrePatron property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NombrePatron { get; set; }
#nullable restore
#else
        public string NombrePatron { get; set; }
#endif
        /// <summary>The registroPatronal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegistroPatronal { get; set; }
#nullable restore
#else
        public string RegistroPatronal { get; set; }
#endif
        /// <summary>The salarioBaseCotizacion property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalarioBaseCotizacion { get; set; }
#nullable restore
#else
        public string SalarioBaseCotizacion { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral"/> and sets the default values.
        /// </summary>
        public HistorialLaboralPostResponse_data_historialLaboral()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralPostResponse_data_historialLaboral();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entidadFederativa", n => { EntidadFederativa = n.GetStringValue(); } },
                { "fechaAlta", n => { FechaAlta = n.GetDateValue(); } },
                { "fechaBaja", n => { FechaBaja = n.GetDateValue(); } },
                { "nombrePatron", n => { NombrePatron = n.GetStringValue(); } },
                { "registroPatronal", n => { RegistroPatronal = n.GetStringValue(); } },
                { "salarioBaseCotizacion", n => { SalarioBaseCotizacion = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("entidadFederativa", EntidadFederativa);
            writer.WriteDateValue("fechaAlta", FechaAlta);
            writer.WriteDateValue("fechaBaja", FechaBaja);
            writer.WriteStringValue("nombrePatron", NombrePatron);
            writer.WriteStringValue("registroPatronal", RegistroPatronal);
            writer.WriteStringValue("salarioBaseCotizacion", SalarioBaseCotizacion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
