// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sep\grupo\validar-cedula
    /// </summary>
    public class ValidarCedulaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarCedulaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sep/grupo/validar-cedula?cedula={cedula}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarCedulaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sep/grupo/validar-cedula?cedula={cedula}", rawUrl)
        {
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaPostResponse?> PostAsValidarCedulaPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaPostResponse> PostAsValidarCedulaPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaPostResponse>(requestInfo, KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsValidarCedulaPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedula5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaResponse>(requestInfo, KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,
        /// </summary>
        public class ValidarCedulaRequestBuilderPostQueryParameters 
        {
            /// <summary>Cedula profesional</summary>
            [QueryParameter("cedula")]
            public int? Cedula { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ValidarCedulaRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCedula.ValidarCedulaRequestBuilder.ValidarCedulaRequestBuilderPostQueryParameters>
        {
        }
    }
}
