// <auto-generated/>
using KiotaPosts.Client.Api.Imss.Grupo.ConClinica;
using KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia;
using KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral;
using KiotaPosts.Client.Api.Imss.Grupo.Idse;
using KiotaPosts.Client.Api.Imss.Grupo.LocalizarNss;
using KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf;
using KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss;
using KiotaPosts.Client.Api.Imss.Grupo.UmfAsignada;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imss\grupo
    /// </summary>
    public class GrupoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conClinica property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.ConClinica.ConClinicaRequestBuilder ConClinica
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.ConClinica.ConClinicaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consultarVigencia property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder ConsultarVigencia
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The historialLaboral property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralRequestBuilder HistorialLaboral
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.HistorialLaboral.HistorialLaboralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The idse property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.Idse.IdseRequestBuilder Idse
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.Idse.IdseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The localizarNss property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.LocalizarNss.LocalizarNssRequestBuilder LocalizarNss
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.LocalizarNss.LocalizarNssRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The localizarUmf property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder LocalizarUmf
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The obtenerDatosNss property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder ObtenerDatosNss
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The umfAsignada property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.UmfAsignada.UmfAsignadaRequestBuilder UmfAsignada
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.UmfAsignada.UmfAsignadaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo", rawUrl)
        {
        }
    }
}
