// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imss\grupo\consultar-vigencia
    /// </summary>
    public class ConsultarVigenciaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsultarVigenciaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/consultar-vigencia?curp={curp}&nss={nss}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConsultarVigenciaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/consultar-vigencia?curp={curp}&nss={nss}", rawUrl)
        {
        }
        /// <summary>
        /// Obtiene la vigencia del derecho a servicio medico e incapacidad mediante el envio de un numero de seguro social
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaPostResponse?> PostAsConsultarVigenciaPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaPostResponse> PostAsConsultarVigenciaPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaPostResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene la vigencia del derecho a servicio medico e incapacidad mediante el envio de un numero de seguro social
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsConsultarVigenciaPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigencia5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene la vigencia del derecho a servicio medico e incapacidad mediante el envio de un numero de seguro social
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obtiene la vigencia del derecho a servicio medico e incapacidad mediante el envio de un numero de seguro social
        /// </summary>
        public class ConsultarVigenciaRequestBuilderPostQueryParameters 
        {
            /// <summary>Clave Unica de Registro de Poblacion</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("curp")]
            public string? Curp { get; set; }
#nullable restore
#else
            [QueryParameter("curp")]
            public string Curp { get; set; }
#endif
            /// <summary>Numero de Seguro Social</summary>
            [QueryParameter("nss")]
            public int? Nss { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ConsultarVigenciaRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ConsultarVigencia.ConsultarVigenciaRequestBuilder.ConsultarVigenciaRequestBuilderPostQueryParameters>
        {
        }
    }
}
