// <auto-generated/>
using KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc;
using KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos;
using KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc;
using KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos;
using KiotaPosts.Client.Api.Sat.Grupo.VerificarFirmaElectronica;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\grupo
    /// </summary>
    public class GrupoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The calcularRfc property</summary>
        public KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder CalcularRfc
        {
            get => new KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The obtenerDatos property</summary>
        public KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder ObtenerDatos
        {
            get => new KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The obtenerRfc property</summary>
        public KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder ObtenerRfc
        {
            get => new KiotaPosts.Client.Api.Sat.Grupo.ObtenerRfc.ObtenerRfcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validarDatos property</summary>
        public KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder ValidarDatos
        {
            get => new KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verificarFirmaElectronica property</summary>
        public KiotaPosts.Client.Api.Sat.Grupo.VerificarFirmaElectronica.VerificarFirmaElectronicaRequestBuilder VerificarFirmaElectronica
        {
            get => new KiotaPosts.Client.Api.Sat.Grupo.VerificarFirmaElectronica.VerificarFirmaElectronicaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo", rawUrl)
        {
        }
    }
}
