// <auto-generated/>
using KiotaPosts.Client.Api.Ai.V2.Kie;
using KiotaPosts.Client.Api.Ai.V2.Mrz;
using KiotaPosts.Client.Api.Ai.V2.Templates;
using KiotaPosts.Client.Api.Ai.V2.UniversalOcr;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Ai.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ai\v2
    /// </summary>
    public class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The kie property</summary>
        public KiotaPosts.Client.Api.Ai.V2.Kie.KieRequestBuilder Kie
        {
            get => new KiotaPosts.Client.Api.Ai.V2.Kie.KieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mrz property</summary>
        public KiotaPosts.Client.Api.Ai.V2.Mrz.MrzRequestBuilder Mrz
        {
            get => new KiotaPosts.Client.Api.Ai.V2.Mrz.MrzRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The templates property</summary>
        public KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesRequestBuilder Templates
        {
            get => new KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The universalOcr property</summary>
        public KiotaPosts.Client.Api.Ai.V2.UniversalOcr.UniversalOcrRequestBuilder UniversalOcr
        {
            get => new KiotaPosts.Client.Api.Ai.V2.UniversalOcr.UniversalOcrRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Ai.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Ai.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai/v2", rawUrl)
        {
        }
    }
}
