// <auto-generated/>
using KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito;
using KiotaPosts.Client.Api.Infonavit.Grupo.ObtenerCuenta;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Infonavit.Grupo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\infonavit\grupo
    /// </summary>
    public class GrupoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The buscarCredito property</summary>
        public KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder BuscarCredito
        {
            get => new KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The obtenerCuenta property</summary>
        public KiotaPosts.Client.Api.Infonavit.Grupo.ObtenerCuenta.ObtenerCuentaRequestBuilder ObtenerCuenta
        {
            get => new KiotaPosts.Client.Api.Infonavit.Grupo.ObtenerCuenta.ObtenerCuentaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/infonavit/grupo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.GrupoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrupoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/infonavit/grupo", rawUrl)
        {
        }
    }
}
