// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Sat.V2.Lista69b
{
    [Obsolete("This class is obsolete. Use Lista69bPostResponse instead.")]
    #pragma warning disable CS1591
    public class Lista69bResponse : KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bResponse();
        }
    }
}
