// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\grupo\obtener-datos
    /// </summary>
    public class ObtenerDatosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerDatosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/obtener-datos?rfc={rfc}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerDatosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/obtener-datos?rfc={rfc}", rawUrl)
        {
        }
        /// <summary>
        /// Obten la mayoria de los datos de la constancia de situacion fiscal (CIF) de personas fisicas y morales relacionadas a un RFC (Registro Federal de Contribuyentes) como nombre completo o razon social, codigo postal y regimenes inscritos en el SAT.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse?> PostAsObtenerDatosPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse> PostAsObtenerDatosPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obten la mayoria de los datos de la constancia de situacion fiscal (CIF) de personas fisicas y morales relacionadas a un RFC (Registro Federal de Contribuyentes) como nombre completo o razon social, codigo postal y regimenes inscritos en el SAT.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsObtenerDatosPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatos5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obten la mayoria de los datos de la constancia de situacion fiscal (CIF) de personas fisicas y morales relacionadas a un RFC (Registro Federal de Contribuyentes) como nombre completo o razon social, codigo postal y regimenes inscritos en el SAT.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obten la mayoria de los datos de la constancia de situacion fiscal (CIF) de personas fisicas y morales relacionadas a un RFC (Registro Federal de Contribuyentes) como nombre completo o razon social, codigo postal y regimenes inscritos en el SAT.
        /// </summary>
        public class ObtenerDatosRequestBuilderPostQueryParameters 
        {
            /// <summary>Registro Federal de Contribuyentes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("rfc")]
            public string? Rfc { get; set; }
#nullable restore
#else
            [QueryParameter("rfc")]
            public string Rfc { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ObtenerDatosRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosRequestBuilder.ObtenerDatosRequestBuilderPostQueryParameters>
        {
        }
    }
}
