// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos
{
    [Obsolete("This class is obsolete. Use ObtenerDatosPostResponse instead.")]
    #pragma warning disable CS1591
    public class ObtenerDatosResponse : KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Sat.Grupo.ObtenerDatos.ObtenerDatosResponse();
        }
    }
}
