// <auto-generated/>
using KiotaPosts.Client.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp
{
    /// <summary>
    /// Builds and executes requests for operations under \api\renapo\grupo\valida-curp
    /// </summary>
    public class ValidaCurpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidaCurpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo/grupo/valida-curp?curp={curp}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidaCurpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo/grupo/valida-curp?curp={curp}", rawUrl)
        {
        }
        /// <summary>
        /// Valida CURP API, es una API REST para la obtención y validación de los registros de nacimiento relacionados a la Clave Única de Registro de Población (CURP) en el Registro Nacional de Población (RENAPO) localizados en México en formato JSON. Este endpoint no usa un algoritmo, sino que consulta las fuentes oficiales. Este servicio cumple con la normativa de nuestra parte, te recomendamos leer nuestros nuestros términos y condiciones.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.CurpAPIResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Models.CurpAPIResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder.ValidaCurpRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Models.CurpAPIResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder.ValidaCurpRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.CurpAPIResponse5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Models.CurpAPIResponse>(requestInfo, KiotaPosts.Client.Models.CurpAPIResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida CURP API, es una API REST para la obtención y validación de los registros de nacimiento relacionados a la Clave Única de Registro de Población (CURP) en el Registro Nacional de Población (RENAPO) localizados en México en formato JSON. Este endpoint no usa un algoritmo, sino que consulta las fuentes oficiales. Este servicio cumple con la normativa de nuestra parte, te recomendamos leer nuestros nuestros términos y condiciones.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder.ValidaCurpRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder.ValidaCurpRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Valida CURP API, es una API REST para la obtención y validación de los registros de nacimiento relacionados a la Clave Única de Registro de Población (CURP) en el Registro Nacional de Población (RENAPO) localizados en México en formato JSON. Este endpoint no usa un algoritmo, sino que consulta las fuentes oficiales. Este servicio cumple con la normativa de nuestra parte, te recomendamos leer nuestros nuestros términos y condiciones.
        /// </summary>
        public class ValidaCurpRequestBuilderPostQueryParameters 
        {
            /// <summary>Clave Unica de Registro de Poblacion</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("curp")]
            public string? Curp { get; set; }
#nullable restore
#else
            [QueryParameter("curp")]
            public string Curp { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ValidaCurpRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ValidaCurp.ValidaCurpRequestBuilder.ValidaCurpRequestBuilderPostQueryParameters>
        {
        }
    }
}
