// <auto-generated/>
using KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios;
using KiotaPosts.Client.Api.Imss.Grupo.Idse.ConsultarMovimientosAfiliatorios;
using KiotaPosts.Client.Api.Imss.Grupo.Idse.SeguirLote;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.Idse
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imss\grupo\idse
    /// </summary>
    public class IdseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The capturarMovimientosAfiliatorios property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosRequestBuilder CapturarMovimientosAfiliatorios
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consultarMovimientosAfiliatorios property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.Idse.ConsultarMovimientosAfiliatorios.ConsultarMovimientosAfiliatoriosRequestBuilder ConsultarMovimientosAfiliatorios
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.Idse.ConsultarMovimientosAfiliatorios.ConsultarMovimientosAfiliatoriosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seguirLote property</summary>
        public KiotaPosts.Client.Api.Imss.Grupo.Idse.SeguirLote.SeguirLoteRequestBuilder SeguirLote
        {
            get => new KiotaPosts.Client.Api.Imss.Grupo.Idse.SeguirLote.SeguirLoteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.Idse.IdseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/idse", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.Idse.IdseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/idse", rawUrl)
        {
        }
    }
}
