// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\grupo\calcular-rfc
    /// </summary>
    public class CalcularRfcRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalcularRfcRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/calcular-rfc?nombres={nombres}{&anoNacimiento*,diaNacimiento*,materno*,mesNacimiento*,paterno*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalcularRfcRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/calcular-rfc?nombres={nombres}{&anoNacimiento*,diaNacimiento*,materno*,mesNacimiento*,paterno*}", rawUrl)
        {
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,_Nota: no se muestran resultados de cedulas en proceso de titulacion._
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcPostResponse?> PostAsCalcularRfcPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcPostResponse> PostAsCalcularRfcPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcPostResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,_Nota: no se muestran resultados de cedulas en proceso de titulacion._
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsCalcularRfcPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfc5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,_Nota: no se muestran resultados de cedulas en proceso de titulacion._
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Valida la cedula profesional enviada en la base de datos oficial del Registro Nacional de Profesionistas,_Nota: no se muestran resultados de cedulas en proceso de titulacion._
        /// </summary>
        public class CalcularRfcRequestBuilderPostQueryParameters 
        {
            [QueryParameter("anoNacimiento")]
            public int? AnoNacimiento { get; set; }
            [QueryParameter("diaNacimiento")]
            public int? DiaNacimiento { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("materno")]
            public string? Materno { get; set; }
#nullable restore
#else
            [QueryParameter("materno")]
            public string Materno { get; set; }
#endif
            [QueryParameter("mesNacimiento")]
            public int? MesNacimiento { get; set; }
            /// <summary>NOMBRE COMPLETO</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nombres")]
            public string? Nombres { get; set; }
#nullable restore
#else
            [QueryParameter("nombres")]
            public string Nombres { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("paterno")]
            public string? Paterno { get; set; }
#nullable restore
#else
            [QueryParameter("paterno")]
            public string Paterno { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class CalcularRfcRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.CalcularRfc.CalcularRfcRequestBuilder.CalcularRfcRequestBuilderPostQueryParameters>
        {
        }
    }
}
