// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\grupo\validar-datos
    /// </summary>
    public class ValidarDatosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarDatosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/validar-datos{?cp*,nombre*,regimen*,rfc*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarDatosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/grupo/validar-datos{?cp*,nombre*,regimen*,rfc*}", rawUrl)
        {
        }
        /// <summary>
        /// Valida los datos enviados buscando coincidencia con los registros en la base de datos del **SAT.**_Nota: Si el usuario a consultar tiene mas de un regimen, separe los condigo con un_ &quot;|&quot;
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosPostResponse?> PostAsValidarDatosPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosPostResponse> PostAsValidarDatosPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosPostResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida los datos enviados buscando coincidencia con los registros en la base de datos del **SAT.**_Nota: Si el usuario a consultar tiene mas de un regimen, separe los condigo con un_ &quot;|&quot;
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsValidarDatosPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatos5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosResponse>(requestInfo, KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Valida los datos enviados buscando coincidencia con los registros en la base de datos del **SAT.**_Nota: Si el usuario a consultar tiene mas de un regimen, separe los condigo con un_ &quot;|&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Valida los datos enviados buscando coincidencia con los registros en la base de datos del **SAT.**_Nota: Si el usuario a consultar tiene mas de un regimen, separe los condigo con un_ &quot;|&quot;
        /// </summary>
        public class ValidarDatosRequestBuilderPostQueryParameters 
        {
            [QueryParameter("cp")]
            public int? Cp { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nombre")]
            public string? Nombre { get; set; }
#nullable restore
#else
            [QueryParameter("nombre")]
            public string Nombre { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("regimen")]
            public string? Regimen { get; set; }
#nullable restore
#else
            [QueryParameter("regimen")]
            public string Regimen { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("rfc")]
            public string? Rfc { get; set; }
#nullable restore
#else
            [QueryParameter("rfc")]
            public string Rfc { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ValidarDatosRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sat.Grupo.ValidarDatos.ValidarDatosRequestBuilder.ValidarDatosRequestBuilderPostQueryParameters>
        {
        }
    }
}
