// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios
{
    #pragma warning disable CS1591
    public class CapturarMovimientosAfiliatoriosPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The movimientos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody_movimientos>? Movimientos { get; set; }
#nullable restore
#else
        public List<KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody_movimientos> Movimientos { get; set; }
#endif
        /// <summary>Please provide a valid URL format. Here, we provide you with the IDSE response to confirm your request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Webhook { get; set; }
#nullable restore
#else
        public string Webhook { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody"/> and sets the default values.
        /// </summary>
        public CapturarMovimientosAfiliatoriosPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "movimientos", n => { Movimientos = n.GetCollectionOfObjectValues<KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody_movimientos>(KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody_movimientos.CreateFromDiscriminatorValue)?.ToList(); } },
                { "webhook", n => { Webhook = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<KiotaPosts.Client.Api.Imss.Grupo.Idse.CapturarMovimientosAfiliatorios.CapturarMovimientosAfiliatoriosPostRequestBody_movimientos>("movimientos", Movimientos);
            writer.WriteStringValue("webhook", Webhook);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
