// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum ValidCURPUserData_sexo
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "HOMBRE")]
        #pragma warning disable CS1591
        HOMBRE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MUJER")]
        #pragma warning disable CS1591
        MUJER,
        #pragma warning restore CS1591
    }
}
