// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class ValidCURPUserData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apellidoMaterno property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApellidoMaterno { get; set; }
#nullable restore
#else
        public string ApellidoMaterno { get; set; }
#endif
        /// <summary>The apellidoPaterno property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApellidoPaterno { get; set; }
#nullable restore
#else
        public string ApellidoPaterno { get; set; }
#endif
        /// <summary>The curp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Curp { get; set; }
#nullable restore
#else
        public string Curp { get; set; }
#endif
        /// <summary>The datosDocProbatorio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.DocProbatorioData? DatosDocProbatorio { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.DocProbatorioData DatosDocProbatorio { get; set; }
#endif
        /// <summary>The docProbatorio property</summary>
        public int? DocProbatorio { get; set; }
        /// <summary>The estadoNacimiento property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EstadoNacimiento { get; set; }
#nullable restore
#else
        public string EstadoNacimiento { get; set; }
#endif
        /// <summary>The fechaNacimiento property</summary>
        public Date? FechaNacimiento { get; set; }
        /// <summary>The historial property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.HistorialData? Historial { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.HistorialData Historial { get; set; }
#endif
        /// <summary>The nombres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nombres { get; set; }
#nullable restore
#else
        public string Nombres { get; set; }
#endif
        /// <summary>The paisNacimiento property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaisNacimiento { get; set; }
#nullable restore
#else
        public string PaisNacimiento { get; set; }
#endif
        /// <summary>The sexo property</summary>
        public KiotaPosts.Client.Models.ValidCURPUserData_sexo? Sexo { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Models.ValidCURPUserData"/> and sets the default values.
        /// </summary>
        public ValidCURPUserData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.ValidCURPUserData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Models.ValidCURPUserData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.ValidCURPUserData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apellidoMaterno", n => { ApellidoMaterno = n.GetStringValue(); } },
                { "apellidoPaterno", n => { ApellidoPaterno = n.GetStringValue(); } },
                { "curp", n => { Curp = n.GetStringValue(); } },
                { "datosDocProbatorio", n => { DatosDocProbatorio = n.GetObjectValue<KiotaPosts.Client.Models.DocProbatorioData>(KiotaPosts.Client.Models.DocProbatorioData.CreateFromDiscriminatorValue); } },
                { "docProbatorio", n => { DocProbatorio = n.GetIntValue(); } },
                { "estadoNacimiento", n => { EstadoNacimiento = n.GetStringValue(); } },
                { "fechaNacimiento", n => { FechaNacimiento = n.GetDateValue(); } },
                { "historial", n => { Historial = n.GetObjectValue<KiotaPosts.Client.Models.HistorialData>(KiotaPosts.Client.Models.HistorialData.CreateFromDiscriminatorValue); } },
                { "nombres", n => { Nombres = n.GetStringValue(); } },
                { "paisNacimiento", n => { PaisNacimiento = n.GetStringValue(); } },
                { "sexo", n => { Sexo = n.GetEnumValue<KiotaPosts.Client.Models.ValidCURPUserData_sexo>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apellidoMaterno", ApellidoMaterno);
            writer.WriteStringValue("apellidoPaterno", ApellidoPaterno);
            writer.WriteStringValue("curp", Curp);
            writer.WriteObjectValue<KiotaPosts.Client.Models.DocProbatorioData>("datosDocProbatorio", DatosDocProbatorio);
            writer.WriteIntValue("docProbatorio", DocProbatorio);
            writer.WriteStringValue("estadoNacimiento", EstadoNacimiento);
            writer.WriteDateValue("fechaNacimiento", FechaNacimiento);
            writer.WriteObjectValue<KiotaPosts.Client.Models.HistorialData>("historial", Historial);
            writer.WriteStringValue("nombres", Nombres);
            writer.WriteStringValue("paisNacimiento", PaisNacimiento);
            writer.WriteEnumValue<KiotaPosts.Client.Models.ValidCURPUserData_sexo>("sexo", Sexo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
