// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp
{
    #pragma warning disable CS1591
    public class ObtenerCurpPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apellidoMaterno property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApellidoMaterno { get; set; }
#nullable restore
#else
        public string ApellidoMaterno { get; set; }
#endif
        /// <summary>The apellidoPaterno property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApellidoPaterno { get; set; }
#nullable restore
#else
        public string ApellidoPaterno { get; set; }
#endif
        /// <summary>The curp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Curp { get; set; }
#nullable restore
#else
        public string Curp { get; set; }
#endif
        /// <summary>The fechaNacimiento property</summary>
        public Date? FechaNacimiento { get; set; }
        /// <summary>The mensaje property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mensaje { get; set; }
#nullable restore
#else
        public string Mensaje { get; set; }
#endif
        /// <summary>The nombres property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nombres { get; set; }
#nullable restore
#else
        public string Nombres { get; set; }
#endif
        /// <summary>The sexo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sexo { get; set; }
#nullable restore
#else
        public string Sexo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse_data"/> and sets the default values.
        /// </summary>
        public ObtenerCurpPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apellidoMaterno", n => { ApellidoMaterno = n.GetStringValue(); } },
                { "apellidoPaterno", n => { ApellidoPaterno = n.GetStringValue(); } },
                { "curp", n => { Curp = n.GetStringValue(); } },
                { "fechaNacimiento", n => { FechaNacimiento = n.GetDateValue(); } },
                { "mensaje", n => { Mensaje = n.GetStringValue(); } },
                { "nombres", n => { Nombres = n.GetStringValue(); } },
                { "sexo", n => { Sexo = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apellidoMaterno", ApellidoMaterno);
            writer.WriteStringValue("apellidoPaterno", ApellidoPaterno);
            writer.WriteStringValue("curp", Curp);
            writer.WriteDateValue("fechaNacimiento", FechaNacimiento);
            writer.WriteStringValue("mensaje", Mensaje);
            writer.WriteStringValue("nombres", Nombres);
            writer.WriteStringValue("sexo", Sexo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
