// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp
{
    /// <summary>
    /// Builds and executes requests for operations under \api\renapo\grupo\obtener-curp
    /// </summary>
    public class ObtenerCurpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerCurpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo/grupo/obtener-curp{?anoNacimiento*,claveEntidad*,diaNacimiento*,materno*,mesNacimiento*,nombres*,paterno*,sexo*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerCurpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/renapo/grupo/obtener-curp{?anoNacimiento*,claveEntidad*,diaNacimiento*,materno*,mesNacimiento*,nombres*,paterno*,sexo*}", rawUrl)
        {
        }
        /// <summary>
        /// Obten la CURP de tus usuarios a traves del envio de sus datos.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse?> PostAsObtenerCurpPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse> PostAsObtenerCurpPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse>(requestInfo, KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obten la CURP de tus usuarios a traves del envio de sus datos.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsObtenerCurpPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurp5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpResponse>(requestInfo, KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obten la CURP de tus usuarios a traves del envio de sus datos.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obten la CURP de tus usuarios a traves del envio de sus datos.
        /// </summary>
        public class ObtenerCurpRequestBuilderPostQueryParameters 
        {
            [QueryParameter("anoNacimiento")]
            public int? AnoNacimiento { get; set; }
            [QueryParameter("claveEntidad")]
            public int? ClaveEntidad { get; set; }
            [QueryParameter("diaNacimiento")]
            public int? DiaNacimiento { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("materno")]
            public string? Materno { get; set; }
#nullable restore
#else
            [QueryParameter("materno")]
            public string Materno { get; set; }
#endif
            [QueryParameter("mesNacimiento")]
            public int? MesNacimiento { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nombres")]
            public string? Nombres { get; set; }
#nullable restore
#else
            [QueryParameter("nombres")]
            public string Nombres { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("paterno")]
            public string? Paterno { get; set; }
#nullable restore
#else
            [QueryParameter("paterno")]
            public string Paterno { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sexo")]
            public string? Sexo { get; set; }
#nullable restore
#else
            [QueryParameter("sexo")]
            public string Sexo { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ObtenerCurpRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Renapo.Grupo.ObtenerCurp.ObtenerCurpRequestBuilder.ObtenerCurpRequestBuilderPostQueryParameters>
        {
        }
    }
}
