// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Api.Ai.V2.Templates
{
    [Obsolete("This class is obsolete. Use TemplatesPutResponse instead.")]
    #pragma warning disable CS1591
    public class TemplatesResponse : KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesPutResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Api.Ai.V2.Templates.TemplatesResponse();
        }
    }
}
