// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ai\grupo\procesamiento-masivo
    /// </summary>
    public class ProcesamientoMasivoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProcesamientoMasivoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai/grupo/procesamiento-masivo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProcesamientoMasivoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ai/grupo/procesamiento-masivo", rawUrl)
        {
        }
        /// <summary>
        /// Procesa los archivos, bases de datos y webs que necesites, integra de manera fluida servicios tanto de API Market como externos, escala con nuestro clúster, elimina el ruido de los rate limit y proxies.
        /// </summary>
        /// <returns>A List&lt;string&gt;</returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<string>?> PostAsync(KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<string>> PostAsync(KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivo5XXError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendPrimitiveCollectionAsync<string>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.ToList();
        }
        /// <summary>
        /// Procesa los archivos, bases de datos y webs que necesites, integra de manera fluida servicios tanto de API Market como externos, escala con nuestro clúster, elimina el ruido de los rate limit y proxies.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Ai.Grupo.ProcesamientoMasivo.ProcesamientoMasivoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ProcesamientoMasivoRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
