// <auto-generated/>
using KiotaPosts.Client.Api.Sat.V2.Lista69b;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.Sat.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sat\v2
    /// </summary>
    public class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lista69b property</summary>
        public KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bRequestBuilder Lista69b
        {
            get => new KiotaPosts.Client.Api.Sat.V2.Lista69b.Lista69bRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sat.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sat/v2", rawUrl)
        {
        }
    }
}
