// <auto-generated/>
using KiotaPosts.Client.Api.V2.Apimarket.Permissions;
using KiotaPosts.Client.Api.V2.Apimarket.PublicKey;
using KiotaPosts.Client.Api.V2.Apimarket.Tokens;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Api.V2.Apimarket
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\apimarket
    /// </summary>
    public class ApimarketRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The permissions property</summary>
        public KiotaPosts.Client.Api.V2.Apimarket.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new KiotaPosts.Client.Api.V2.Apimarket.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The publicKey property</summary>
        public KiotaPosts.Client.Api.V2.Apimarket.PublicKey.PublicKeyRequestBuilder PublicKey
        {
            get => new KiotaPosts.Client.Api.V2.Apimarket.PublicKey.PublicKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokens property</summary>
        public KiotaPosts.Client.Api.V2.Apimarket.Tokens.TokensRequestBuilder Tokens
        {
            get => new KiotaPosts.Client.Api.V2.Apimarket.Tokens.TokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.V2.Apimarket.ApimarketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApimarketRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/apimarket", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.V2.Apimarket.ApimarketRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApimarketRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/apimarket", rawUrl)
        {
        }
    }
}
