// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imss\grupo\localizar-umf
    /// </summary>
    public class LocalizarUmfRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocalizarUmfRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/localizar-umf?cp={cp}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocalizarUmfRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/localizar-umf?cp={cp}", rawUrl)
        {
        }
        /// <summary>
        /// Obtiene las clinicas que brindan atencion medica a los habitantes de ese codigo postal, las clinicas mas cercanas y posibles asignadas, brinda coordenadas de ubicacion, direccion y numero de contacto de cada clinica.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfPostResponse?> PostAsLocalizarUmfPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfPostResponse> PostAsLocalizarUmfPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfPostResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene las clinicas que brindan atencion medica a los habitantes de ese codigo postal, las clinicas mas cercanas y posibles asignadas, brinda coordenadas de ubicacion, direccion y numero de contacto de cada clinica.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsLocalizarUmfPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf401Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmf5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene las clinicas que brindan atencion medica a los habitantes de ese codigo postal, las clinicas mas cercanas y posibles asignadas, brinda coordenadas de ubicacion, direccion y numero de contacto de cada clinica.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obtiene las clinicas que brindan atencion medica a los habitantes de ese codigo postal, las clinicas mas cercanas y posibles asignadas, brinda coordenadas de ubicacion, direccion y numero de contacto de cada clinica.
        /// </summary>
        public class LocalizarUmfRequestBuilderPostQueryParameters 
        {
            /// <summary>Codigo Postal</summary>
            [QueryParameter("cp")]
            public int? Cp { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class LocalizarUmfRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.LocalizarUmf.LocalizarUmfRequestBuilder.LocalizarUmfRequestBuilderPostQueryParameters>
        {
        }
    }
}
