// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado
{
    /// <summary>
    /// Builds and executes requests for operations under \api\sep\grupo\validar-certificado
    /// </summary>
    public class ValidarCertificadoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarCertificadoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sep/grupo/validar-certificado{?folio*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidarCertificadoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/sep/grupo/validar-certificado{?folio*}", rawUrl)
        {
        }
        /// <summary>
        /// Busqueda de folio electronico de certificados en el sistema DGETI de la Secretaria de Educacion Publica._Nota: Solo podran ser consultados los certificados que se encuentren Digitalizados (Que tengan QR)_
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoPostResponse?> PostAsValidarCertificadoPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoPostResponse> PostAsValidarCertificadoPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoPostResponse>(requestInfo, KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Busqueda de folio electronico de certificados en el sistema DGETI de la Secretaria de Educacion Publica._Nota: Solo podran ser consultados los certificados que se encuentren Digitalizados (Que tengan QR)_
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsValidarCertificadoPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado404Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificado5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoResponse>(requestInfo, KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Busqueda de folio electronico de certificados en el sistema DGETI de la Secretaria de Educacion Publica._Nota: Solo podran ser consultados los certificados que se encuentren Digitalizados (Que tengan QR)_
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Busqueda de folio electronico de certificados en el sistema DGETI de la Secretaria de Educacion Publica._Nota: Solo podran ser consultados los certificados que se encuentren Digitalizados (Que tengan QR)_
        /// </summary>
        public class ValidarCertificadoRequestBuilderPostQueryParameters 
        {
            /// <summary>Folio Electronico del certificado</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folio")]
            public string? Folio { get; set; }
#nullable restore
#else
            [QueryParameter("folio")]
            public string Folio { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ValidarCertificadoRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Sep.Grupo.ValidarCertificado.ValidarCertificadoRequestBuilder.ValidarCertificadoRequestBuilderPostQueryParameters>
        {
        }
    }
}
