// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss
{
    /// <summary>
    /// Builds and executes requests for operations under \api\imss\grupo\obtener-datos-nss
    /// </summary>
    public class ObtenerDatosNssRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerDatosNssRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/obtener-datos-nss?nss={nss}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ObtenerDatosNssRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/imss/grupo/obtener-datos-nss?nss={nss}", rawUrl)
        {
        }
        /// <summary>
        /// Obtiene los datos oficiales registrados en el IMSS de un Numero de Seguro Social.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNss400Error">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssPostResponse?> PostAsObtenerDatosNssPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssPostResponse> PostAsObtenerDatosNssPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNss400Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssPostResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene los datos oficiales registrados en el IMSS de un Numero de Seguro Social.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNss400Error">When receiving a 400 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsObtenerDatosNssPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNss400Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssResponse>(requestInfo, KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Obtiene los datos oficiales registrados en el IMSS de un Numero de Seguro Social.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Obtiene los datos oficiales registrados en el IMSS de un Numero de Seguro Social.
        /// </summary>
        public class ObtenerDatosNssRequestBuilderPostQueryParameters 
        {
            /// <summary>Numero de Seguro Social</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nss")]
            public string? Nss { get; set; }
#nullable restore
#else
            [QueryParameter("nss")]
            public string Nss { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class ObtenerDatosNssRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Imss.Grupo.ObtenerDatosNss.ObtenerDatosNssRequestBuilder.ObtenerDatosNssRequestBuilderPostQueryParameters>
        {
        }
    }
}
