// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito
{
    /// <summary>
    /// Builds and executes requests for operations under \api\infonavit\grupo\buscar-credito
    /// </summary>
    public class BuscarCreditoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BuscarCreditoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/infonavit/grupo/buscar-credito?nss={nss}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BuscarCreditoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/infonavit/grupo/buscar-credito?nss={nss}", rawUrl)
        {
        }
        /// <summary>
        /// Endpoint para realizar la consulta de creditos en el infonavit, obtenida mediante el Numero de seguro social de la persona.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito422Error">When receiving a 422 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito5XXError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoPostResponse?> PostAsBuscarCreditoPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoPostResponse> PostAsBuscarCreditoPostResponseAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito404Error.CreateFromDiscriminatorValue },
                { "422", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito422Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoPostResponse>(requestInfo, KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Endpoint para realizar la consulta de creditos en el infonavit, obtenida mediante el Numero de seguro social de la persona.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito400Error">When receiving a 400 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito401Error">When receiving a 401 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito404Error">When receiving a 404 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito422Error">When receiving a 422 status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito4XXError">When receiving a 4XX status code</exception>
        /// <exception cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito5XXError">When receiving a 5XX status code</exception>
        [Obsolete("This method is obsolete. Use PostAsBuscarCreditoPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoResponse?> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoResponse> PostAsync(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito400Error.CreateFromDiscriminatorValue },
                { "401", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito401Error.CreateFromDiscriminatorValue },
                { "404", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito404Error.CreateFromDiscriminatorValue },
                { "422", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito422Error.CreateFromDiscriminatorValue },
                { "4XX", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito4XXError.CreateFromDiscriminatorValue },
                { "5XX", KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCredito5XXError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoResponse>(requestInfo, KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Endpoint para realizar la consulta de creditos en el infonavit, obtenida mediante el Numero de seguro social de la persona.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Endpoint para realizar la consulta de creditos en el infonavit, obtenida mediante el Numero de seguro social de la persona.
        /// </summary>
        public class BuscarCreditoRequestBuilderPostQueryParameters 
        {
            /// <summary>Número de Seguro Social</summary>
            [QueryParameter("nss")]
            public int? Nss { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class BuscarCreditoRequestBuilderPostRequestConfiguration : RequestConfiguration<KiotaPosts.Client.Api.Infonavit.Grupo.BuscarCredito.BuscarCreditoRequestBuilder.BuscarCreditoRequestBuilderPostQueryParameters>
        {
        }
    }
}
